name: 
  First Workflow

on:
  workflow_dispatch

jobs:
  # specify job names - can be anything
  first-job:
    runs-on:
      ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello World!"
          echo "This is multiline"
          echo "echo statement."
      - name: Goodbye
        run:
          echo "Goodbye!"
