name: 
  First Workflow

on:
  # https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#using-activity-types-and-filters-with-multiple-events
  # append : if more trigger events are specified
  workflow_dispatch:
  push:

jobs:
  # specify job names - can be anything
  first-job:
    runs-on:
      ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello World!"
          echo "This is multiline"
          echo "echo statement."
      - name: Goodbye
        run:
          echo "Goodbye!"
